const mongoose = require('mongoose')

const UserSchema = new mongoose.Schema({
    userId: Number,           // generated by code
    username: String,         // used to sign in
    name: String,             // First Name Last Name (Format)
    phoneNumber: Number,
    password: String,
    status: {
        type: String,
        enum: ["Customer", "Employee", "Owner"],
        default: "Customer",
    },
    securityQuestions: [],     // to be filled out by the code (Ex: [1,2,4])
    secAns1: String,           // Security answer 1
    secAns2: String,           // Security answer 2
    secAns3: String,           // Security answer 3
    passwordHistory: [],       // Array of previous passwords
    lastChanged: String,       // format: mm-dd-yyyy hh:mm:ss am/pm
    failedLoginAttempts: {
        type: Number,
        default: 0
    },
    accountLocked: {
        type: Boolean,
        default: false
    },
    lockUntil: Date,           // When the account will be unlocked
    lastLoginAttempt: Date,    // Track last login attempt
    lastLoginAttemptIP: String, // IP address of last login attempt
    lastLoginAttemptSuccess: Boolean, // Whether last attempt was successful
    loginHistory: [{           // Track successful logins
        timestamp: Date,
        ipAddress: String
    }]
})

const User = mongoose.model('User', UserSchema)

module.exports = User