const mongoose = require('mongoose')

const UserSchema = new mongoose.Schema({
    userId: String,           // generated by code
    username: String,         // used to sign in
    name: String,             // First Name, Last Name (Format)
    password: String,
    status: {
        type: String,
        enum: ["Customer", "Employee", "Owner"],
        default: "Customer",
    },
    securityQuestions: [],     // to be filled out by the code (Ex: [1,2,4,5,7])
    secAns1: String,           // First pet's name (Sample)
    secAns2: String,           // Mother's maiden name (Sample)
    secAns3: String,           // Childhood Nickname (Sample)
    secAns4: String,           // Name of the first school you attended (Sample)
    secAns5: String,           // Favorite subject in high school (Sample)
    passwordHistory: [],
    lastChanged: String,        //format: mm-dd-yyyy hh:mm:ss am/pm
})

const User = mongoose.model('User', UserSchema)

module.exports = User